CREATE TABLE IF NOT EXISTS favorites (
    id SERIAL PRIMARY KEY,
    city TEXT NOT NULL UNIQUE,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
